import { IMenuViewModel } from "../../../model/respone/auth/IMenuViewModel";

export const menusSample: IMenuViewModel[] = [
  {
    id: 1,
    name: "Tài nguyên",
    description: "",
    is_active: true,
    icon: "profits.png",
    menu_id_parent: 0,
    name_en: "",
    path: "",
    sort_idx: "",
    sub_system_id: 0,
    items: [
      {
        id: 10,
        name: "Đề cương môn học",
        description: "",
        is_active: true,
        icon: "BiCategoryAlt",
        items: [],
        menu_id_parent: 1,
        name_en: "",
        path: "de-cuong",
        sort_idx: "",
        sub_system_id: 0,
      },
    ],
  },
  {
    id: 2,
    name: "Danh mục",
    description: "",
    is_active: true,
    icon: "profits.png",
    menu_id_parent: 0,
    name_en: "",
    path: "",
    sort_idx: "",
    sub_system_id: 0,
    items: [
      {
        id: 52,
        name: "Bộ môn",
        description: "",
        is_active: true,
        icon: "BiCategoryAlt",
        items: [],
        menu_id_parent: 1,
        name_en: "",
        path: "bo-mon",
        sort_idx: "",
        sub_system_id: 0,
      },
      {
        id: 50,
        name: "Môn học",
        description: "",
        is_active: true,
        icon: "BiCategoryAlt",
        items: [],
        menu_id_parent: 1,
        name_en: "",
        path: "mon-hoc",
        sort_idx: "",
        sub_system_id: 0,
      },
      {
        id: 51,
        name: "Giáo viên",
        description: "",
        is_active: true,
        icon: "BiCategoryAlt",
        items: [],
        menu_id_parent: 1,
        name_en: "",
        path: "giao-vien",
        sort_idx: "",
        sub_system_id: 0,
      },
      {
        id: 53,
        name: "Chuẩn đầu ra",
        description: "",
        is_active: true,
        icon: "BiCategoryAlt",
        items: [],
        menu_id_parent: 1,
        name_en: "",
        path: "chuan-dau-ra",
        sort_idx: "",
        sub_system_id: 0,
      },
    ],
  },
  {
    id: 3,
    name: "Phân quyền",
    description: "",
    is_active: true,
    icon: "profits.png",
    menu_id_parent: 0,
    name_en: "",
    path: "",
    sort_idx: "",
    sub_system_id: 0,
    items: [
      {
        id: 1,
        name: "Phê duyệt",
        description: "",
        is_active: true,
        icon: "BiCategoryAlt",
        items: [],
        menu_id_parent: 1,
        name_en: "",
        path: "phe-duyet",
        sort_idx: "",
        sub_system_id: 0,
      },
    ],
  },
];
